(() => {
  const subcategories = {
    Autot: [['Henkilöautot','🚗'],['Pakettiautot','🚐'],['Moottoripyörät','🏍️'],['Mopot & skootterit','🛵'],['Veneet','🛥️'],['Matkailuautot & vaunut','🚐'],['Renkaat & vanteet','🛞'],['Varaosat','⚙️'],['Autotarvikkeet','🧰'],['Muut ajoneuvot','🚜']],
    Koti: [['Sohvat & nojatuolit','🛋️'],['Pöydät & tuolit','🪑'],['Sängyt & patjat','🛏️'],['Kaapit & säilytys','🗄️'],['Valaisimet','💡'],['Kodinkoneet','🧺'],['Keittiö','🍽️'],['Sisustus','🖼️'],['Piha & puutarha','🌿'],['Työkalut','🛠️']],
    Elektroniikka: [['Puhelimet','📱'],['Tabletit','📲'],['Televisiot','📺'],['Tietokoneet','💻'],['Ääni & kuulokkeet','🎧'],['Kamerat','📷'],['Pelikonsolit','🎮'],['Älykellot','⌚'],['Tarvikkeet','🔌'],['Muu elektroniikka','🔋']],
    Vaatteet: [['Naisten vaatteet','👗'],['Miesten vaatteet','👔'],['Lasten vaatteet','🧒'],['Kengät','👟'],['Laukut','👜'],['Korut & kellot','💍'],['Urheiluvaatteet','🏃'],['Asusteet','🧢'],['Juhlavaatteet','✨'],['Muut vaatteet','👕']],
    Työt: [['Kuljetus & logistiikka','🚚'],['Rakennus','🏗️'],['Ravintola & hotelli','🍽️'],['Myynti & asiakaspalvelu','🛍️'],['Siivous','🧹'],['Hoito & terveys','🩺'],['IT & teknologia','💻'],['Toimisto','🗂️'],['Teollisuus','🏭'],['Muut työt','💼']],
    Palvelut: [['Muuttoapu','📦'],['Siivous','🧹'],['Remontti','🔨'],['Autopalvelut','🔧'],['Kuljetus','🚚'],['Kauneus & hyvinvointi','💇'],['Opetus & kurssit','📚'],['IT-apu','🖥️'],['Valokuvaus','📸'],['Muut palvelut','🧰']],
    Asunnot: [['Kerrostalo','🏢'],['Rivitalo','🏘️'],['Omakotitalo','🏡'],['Paritalo','🏠'],['Mökki','🌲'],['Tontti','📐'],['Autotalli & varasto','🚪'],['Liiketila','🏬'],['Huone','🛏️'],['Muu asunto','🏠']]
  };
  const searchAliases={
    'Henkilöautot':'henkiloauto henkilöauto autot auto car cars','Pakettiautot':'pakettiauto van','Moottoripyörät':'moottoripyora moottoripyörä motorcycle','Mopot & skootterit':'mopo skootteri scooter','Varaosat':'varaosa autonosat osat','Autotarvikkeet':'autotarvike tarvikkeet','Puhelimet':'puhelin puhelimet phone mobile kännykkä iphone android','Tabletit':'tabletti ipad tablet','Televisiot':'televisio tv television','Tietokoneet':'tietokone laptop kannettava pc computer','Ääni & kuulokkeet':'kuulokkeet kuuloke airpods kaiutin audio','Kerrostalo':'kerrostalo asunto apartment','Rivitalo':'rivitalo asunto','Omakotitalo':'omakotitalo talo house','Vuokra':'vuokra vuokrataan vuokra-asunto rent rental','Myynti':'myynti myydään myytävä asunto sale'
  };
  let subtypeFilter = '', housingStage = 'choice';
  const style=document.createElement('style');style.textContent=`.subcategory-panel{display:none;margin-top:14px;padding:16px;background:#fff;border:1px solid #e4e7eb;border-radius:16px}.subcategory-panel.show{display:block}.subcategory-panel h3{margin:0 0 12px;font-size:16px}.subcategory-chips{display:flex;gap:8px;flex-wrap:wrap}.subcategory-chips button{background:#f8fafc;color:#334155;border:1px solid #e2e8f0;padding:9px 12px;border-radius:999px;font-size:13px}.subcategory-chips button:hover,.subcategory-chips button.active{background:#1565d8;color:#fff;border-color:#1565d8}.subcategory-tag{display:inline-block;margin-top:8px;margin-left:6px;background:#eef4ff;color:#1565d8;border-radius:999px;padding:5px 8px;font-size:11px;font-weight:800}.housing-choice-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.housing-choice{min-height:92px;border-radius:16px!important;font-size:17px!important;display:flex;align-items:center;justify-content:center;gap:8px;background:#f8fafc!important;color:#17202a!important;border:1px solid #dbe3ee!important}.housing-choice:hover,.housing-choice.active{background:#1565d8!important;color:#fff!important;border-color:#1565d8!important}.housing-back{margin-bottom:12px;background:#eef4ff;color:#1565d8}@media(max-width:700px){.housing-choice-grid{grid-template-columns:1fr}.housing-choice{min-height:74px}}`;document.head.appendChild(style);
  const categories=document.querySelector('.categories'),categorySelect=document.querySelector('#category'),housingWrap=document.querySelector('#housingTypeWrap');if(!categories||!categorySelect)return;
  const panel=document.createElement('div');panel.className='subcategory-panel';categories.insertAdjacentElement('afterend',panel);
  const subtypeWrap=document.createElement('label');subtypeWrap.innerHTML=`Alaluokka<select id="subtype"></select>`;housingWrap?.insertAdjacentElement('afterend',subtypeWrap);const subtypeSelect=subtypeWrap.querySelector('select');
  function syncSubtypeForm(){const types=subcategories[categorySelect.value]||[];subtypeWrap.hidden=!types.length;subtypeSelect.innerHTML=types.map(([n])=>`<option>${n}</option>`).join('')}categorySelect.addEventListener('change',syncSubtypeForm);syncSubtypeForm();
  function renderHousingTypes(){const types=subcategories.Asunnot;panel.innerHTML=`<button type="button" class="housing-back">← Takaisin</button><h3>${housingFilter==='Myynti'?'Myytävät asunnot':'Vuokra-asunnot'} – asuntotyyppi</h3><div class="subcategory-chips">${types.map(([n,i])=>`<button type="button" data-subtype="${n}" class="${subtypeFilter===n?'active':''}">${i} ${n}</button>`).join('')}</div>`;panel.classList.add('show');panel.querySelector('.housing-back').onclick=()=>{housingStage='choice';subtypeFilter='';render()};panel.querySelectorAll('[data-subtype]').forEach(b=>b.onclick=()=>{subtypeFilter=subtypeFilter===b.dataset.subtype?'':b.dataset.subtype;render()})}
  function renderPanel(){if(filter==='Asunnot'){if(housingStage==='types'&&housingFilter){renderHousingTypes();return}panel.innerHTML=`<h3>Asunnot</h3><div class="housing-choice-grid"><button type="button" class="housing-choice" data-housing-choice="Myynti">🏡 Myytävät asunnot</button><button type="button" class="housing-choice" data-housing-choice="Vuokra">🔑 Vuokra-asunnot</button></div>`;panel.classList.add('show');panel.querySelectorAll('[data-housing-choice]').forEach(b=>b.onclick=()=>{housingFilter=b.dataset.housingChoice;housingStage='types';subtypeFilter='';filter='Asunnot';render()});return}const types=subcategories[filter]||[];if(!types.length){panel.classList.remove('show');panel.innerHTML='';return}panel.innerHTML=`<h3>${escapeHtml(filter)} – alaluokat</h3><div class="subcategory-chips">${types.map(([n,i])=>`<button type="button" data-subtype="${n}" class="${subtypeFilter===n?'active':''}">${i} ${n}</button>`).join('')}</div>`;panel.classList.add('show');panel.querySelectorAll('[data-subtype]').forEach(b=>b.onclick=()=>{subtypeFilter=subtypeFilter===b.dataset.subtype?'':b.dataset.subtype;render()})}
  const oldRender=render;render=function(){const qEl=document.querySelector('#q'),raw=qEl?.value.trim().toLowerCase()||'',allSubs=Object.entries(subcategories).flatMap(([cat,types])=>types.map(([name])=>({cat,name})));let matched=allSubs.filter(s=>s.name.toLowerCase().includes(raw)||(searchAliases[s.name]||'').toLowerCase().includes(raw));if(raw){if(['myynti','myydään','myytävä','sale'].some(k=>raw.includes(k))){filter='Asunnot';housingFilter='Myynti';housingStage='types'}else if(['vuokra','vuokrataan','rent','rental'].some(k=>raw.includes(k))){filter='Asunnot';housingFilter='Vuokra';housingStage='types'}else if(matched.length){const exact=matched.find(s=>s.name.toLowerCase()===raw)||matched[0];filter=exact.cat;subtypeFilter=exact.name;if(filter==='Asunnot'&&!housingFilter)housingStage='choice'}}oldRender();renderPanel();if(subtypeFilter){document.querySelectorAll('#cards .card').forEach(card=>{const item=items.find(x=>x.id===card.dataset.id);const searchable=((item?.subtype||'')+' '+(item?.t||'')+' '+(item?.desc||'')).toLowerCase();if(!item||(!searchable.includes(subtypeFilter.toLowerCase())&&item.subtype!==subtypeFilter))card.style.display='none'});const visible=[...document.querySelectorAll('#cards .card')].some(c=>c.style.display!=='none');if(!visible)cards.innerHTML='<p class="empty">Ei ilmoituksia tässä alaluokassa.</p>'}}
  document.querySelectorAll('[data-cat]').forEach(btn=>{const prev=btn.onclick;btn.onclick=e=>{prev?.call(btn,e);subtypeFilter='';if(btn.dataset.cat==='Asunnot'&&filter==='Asunnot'){housingFilter='';housingStage='choice'}else housingStage='choice';render()}});
  const form=document.querySelector('#form'),oldSubmit=form.onsubmit;form.onsubmit=e=>{const cat=categorySelect.value,sub=(subcategories[cat]||[]).length?subtypeSelect.value:'';oldSubmit(e);const newest=items.find(x=>x.id?.startsWith('user-')&&x.c===cat&&!x.subtype);if(newest&&sub){newest.subtype=sub;persist();filter=cat;subtypeFilter=sub;if(cat==='Asunnot'){housingStage='types';housingFilter=newest.housingType||''}render()}syncSubtypeForm()};
  const allBtn=document.querySelector('#all'),oldAll=allBtn.onclick;allBtn.onclick=e=>{subtypeFilter='';housingStage='choice';oldAll?.call(allBtn,e);render()};render();
})();