(() => {
 const B=window.KaikkiBackend;
 if(!B?.client)return;
 const css=document.createElement('style');
 css.textContent=`.chat-modal .panel{max-width:620px}.chat-head{padding-right:38px;margin-bottom:12px}.chat-head h3{margin:0}.chat-sub{font-size:13px;color:#64748b;margin-top:4px}.chat-list{height:min(420px,55vh);overflow:auto;border:1px solid #e5e7eb;border-radius:14px;padding:12px;background:#f8fafc;display:flex;flex-direction:column;gap:8px}.chat-bubble{max-width:82%;padding:10px 12px;border-radius:14px;background:#fff;border:1px solid #e5e7eb;align-self:flex-start}.chat-bubble.mine{background:#1565d8;color:#fff;border-color:#1565d8;align-self:flex-end}.chat-bubble small{display:block;margin-top:5px;opacity:.7}.chat-compose{display:grid;grid-template-columns:1fr auto;gap:8px;margin-top:10px}.chat-compose input{width:100%;padding:11px;border:1px solid #d8dde5;border-radius:10px}.thread-row{width:100%;display:flex!important;justify-content:space-between;gap:12px;text-align:left!important;background:#fff!important;color:#17202a!important;border:1px solid #e5e7eb!important;margin:8px 0;padding:12px!important}.thread-main{min-width:0}.thread-title{font-weight:800}.thread-preview{font-size:13px;color:#64748b;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:320px}.thread-meta{font-size:12px;color:#94a3b8;margin-top:4px}.thread-unread{min-width:24px;height:24px;border-radius:999px;background:#dc2626;color:#fff;display:grid;place-items:center;font-size:12px;font-weight:800}.message-empty{padding:20px;color:#64748b;text-align:center}body.kaikki-dark .chat-list,body.kaikki-dark .chat-bubble,body.kaikki-dark .thread-row{background:#111827!important;color:#f8fafc!important;border-color:#374151!important}body.kaikki-dark .thread-preview,body.kaikki-dark .thread-meta,body.kaikki-dark .chat-sub{color:#cbd5e1}`;
 document.head.appendChild(css);
 document.body.insertAdjacentHTML('beforeend',`<div class="modal chat-modal" id="chatModal" aria-hidden="true"><div class="panel"><button class="close" id="chatClose" type="button">×</button><div class="chat-head"><h3 id="chatTitle">Viestit</h3><div class="chat-sub" id="chatSub"></div></div><div class="chat-list" id="chatList"></div><form class="chat-compose" id="chatForm"><input id="chatInput" maxlength="2000" placeholder="Kirjoita viesti..." required><button type="submit">Lähetä</button></form></div></div>`);
 const modal=document.querySelector('#chatModal'),listEl=document.querySelector('#chatList'),titleEl=document.querySelector('#chatTitle'),subEl=document.querySelector('#chatSub'),form=document.querySelector('#chatForm'),input=document.querySelector('#chatInput');
 let active=null;
 const close=()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');active=null};
 document.querySelector('#chatClose').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
 const fmt=v=>{try{return new Date(v).toLocaleString('fi-FI')}catch{return ''}};
 async function drawConversation(){
  if(!active)return;const session=await B.session();if(!session)return;
  listEl.innerHTML='<div class="message-empty">Ladataan...</div>';
  try{const rows=await B.conversation(active.listingId,active.otherUserId);listEl.innerHTML='';if(!rows.length)listEl.innerHTML='<div class="message-empty">Ei viestejä vielä.</div>';
   for(const m of rows){const b=document.createElement('div');b.className='chat-bubble'+(m.sender_id===session.user.id?' mine':'');const text=document.createElement('div');text.textContent=m.body;const time=document.createElement('small');time.textContent=fmt(m.created_at);b.append(text,time);listEl.appendChild(b)}
   await B.markConversationRead(active.listingId,active.otherUserId);listEl.scrollTop=listEl.scrollHeight;
  }catch(e){listEl.innerHTML='<div class="message-empty">Viestien lataus epäonnistui.</div>'}
 }
 async function openConversation(info){active=info;titleEl.textContent=info.listingTitle||'Viestit';subEl.textContent='Keskustelu ilmoituksesta';input.value='';modal.classList.add('show');modal.setAttribute('aria-hidden','false');await drawConversation();setTimeout(()=>input.focus(),50)}
 form.onsubmit=async e=>{e.preventDefault();if(!active)return;const body=input.value.trim();if(!body)return;const btn=form.querySelector('button');btn.disabled=true;try{await B.sendMessage({recipientId:active.otherUserId,listingId:active.listingId,listingTitle:active.listingTitle,body});input.value='';await drawConversation();await renderMessageTab()}catch(err){alert(err?.message||'Viestin lähetys epäonnistui.')}finally{btn.disabled=false}};
 window.KaikkiMessages={open:async listing=>{const session=await B.session();if(!session){document.querySelector('#login')?.click();return}const other=listing.ownerId;if(!other){alert('Tälle demoilmoitukselle ei ole vielä myyjätiliä.');return}if(other===session.user.id){alert('Tämä on oma ilmoituksesi.');return}await openConversation({listingId:listing.dbId||listing.id,listingTitle:listing.t||'Ilmoitus',otherUserId:other})}};
 async function renderMessageTab(){
  const tab=document.querySelector('[data-account-tab="messages"]'),body=document.querySelector('#accountBody');if(!tab?.classList.contains('active')||!body)return;
  body.innerHTML='<div class="message-empty">Ladataan viestejä...</div>';
  try{const session=await B.session();if(!session)return;const rows=await B.messages();const groups=new Map();
   for(const m of rows){const other=m.sender_id===session.user.id?m.recipient_id:m.sender_id;const key=`${m.listing_id}|${other}`;if(!groups.has(key))groups.set(key,{listingId:m.listing_id,listingTitle:m.listing_title,otherUserId:other,last:m,unread:0});const g=groups.get(key);if(new Date(m.created_at)>new Date(g.last.created_at))g.last=m;if(m.recipient_id===session.user.id&&!m.is_read)g.unread++}
   body.innerHTML='<h3>Viestit</h3>';if(!groups.size){body.insertAdjacentHTML('beforeend','<div class="message-empty">Ei viestejä vielä.</div>');return}
   [...groups.values()].sort((a,b)=>new Date(b.last.created_at)-new Date(a.last.created_at)).forEach(g=>{const row=document.createElement('button');row.type='button';row.className='thread-row';const main=document.createElement('div');main.className='thread-main';const t=document.createElement('div');t.className='thread-title';t.textContent=g.listingTitle||'Ilmoitus';const p=document.createElement('div');p.className='thread-preview';p.textContent=g.last.body;const meta=document.createElement('div');meta.className='thread-meta';meta.textContent=fmt(g.last.created_at);main.append(t,p,meta);row.appendChild(main);if(g.unread){const badge=document.createElement('span');badge.className='thread-unread';badge.textContent=g.unread>99?'99+':String(g.unread);row.appendChild(badge)}row.onclick=()=>openConversation(g);body.appendChild(row)})
  }catch(e){body.innerHTML='<div class="message-empty">Viestien lataus epäonnistui.</div>'}
 }
 document.addEventListener('click',e=>{if(e.target.closest?.('[data-account-tab="messages"]'))setTimeout(renderMessageTab,30)});
 const obs=new MutationObserver(()=>{if(document.querySelector('[data-account-tab="messages"]')?.classList.contains('active')&&!document.querySelector('#accountBody .thread-row')&&!document.querySelector('#accountBody .message-empty[data-loading]'))setTimeout(renderMessageTab,20)});obs.observe(document.body,{childList:true,subtree:true,attributes:true});
 window.addEventListener('hashchange',()=>{if(location.hash==='#messages'){document.querySelector('#login')?.click();setTimeout(()=>document.querySelector('[data-account-tab="messages"]')?.click(),120)}});
})();
