import React,{useState}from'react';
import{Alert,Image,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{supabase}from'./supabase';
import{pickListingImages,uploadListingImages}from'./media';

const categories=['Autot','Asunnot','Elektroniikka','Koti','Vaatteet','Työt','Palvelut'];
export default function AdvancedSellManager(){
 const[open,setOpen]=useState(false),[photos,setPhotos]=useState([]),[title,setTitle]=useState(''),[price,setPrice]=useState(''),[city,setCity]=useState('Lahti'),[category,setCategory]=useState('Elektroniikka'),[description,setDescription]=useState(''),[address,setAddress]=useState(''),[publishing,setPublishing]=useState(false);
 async function choosePhotos(){try{const assets=await pickListingImages(8);if(assets.length)setPhotos(assets)}catch(e){Alert.alert('Kuvat',e.message)}}
 function reset(){setPhotos([]);setTitle('');setPrice('');setCity('Lahti');setCategory('Elektroniikka');setDescription('');setAddress('')}
 async function publish(){if(!title.trim()||!city.trim())return Alert.alert('Puuttuvat tiedot','Täytä otsikko ja kaupunki.');const n=Number(price);if(price&&(!Number.isFinite(n)||n<0))return Alert.alert('Hinta','Anna kelvollinen hinta.');setPublishing(true);try{const{data:{session}}=await supabase.auth.getSession();if(!session)throw new Error('Kirjaudu sisään ennen ilmoituksen julkaisua.');const image_urls=photos.length?await uploadListingImages(session.user.id,photos):[];const row={user_id:session.user.id,title:title.trim(),price:n||0,category,city:city.trim(),description:description.trim(),address:address.trim(),condition:'',housing_type:'',extra:{},image_urls};const{error}=await supabase.from('listings').insert(row);if(error)throw error;Alert.alert('Valmis','Ilmoitus julkaistiin.');reset();setOpen(false)}catch(e){Alert.alert('Virhe',e.message)}finally{setPublishing(false)}}
 return <><Pressable style={s.fab} onPress={()=>setOpen(true)}><Text style={s.fabText}>＋ Myy</Text></Pressable><Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={s.page}><View style={s.head}><Pressable onPress={()=>setOpen(false)}><Text style={s.link}>Sulje</Text></Pressable><Text style={s.title}>Uusi ilmoitus</Text><View style={{width:38}}/></View><ScrollView contentContainerStyle={s.form}><Pressable style={s.photoBox} onPress={choosePhotos}><Text style={s.photoEmoji}>📷</Text><Text style={s.photoTitle}>{photos.length?`${photos.length} kuvaa valittu`:'Lisää kuvat'}</Text><Text style={s.help}>Voit valita enintään 8 kuvaa</Text></Pressable>{photos.length>0&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.previews}>{photos.map((p,i)=><Image key={`${p.uri}-${i}`} source={{uri:p.uri}} style={s.preview}/>)}</ScrollView>}<TextInput style={s.input} value={title} onChangeText={setTitle} placeholder="Otsikko"/><TextInput style={s.input} value={price} onChangeText={setPrice} keyboardType="numeric" placeholder="Hinta €"/><TextInput style={s.input} value={city} onChangeText={setCity} placeholder="Kaupunki"/><TextInput style={s.input} value={address} onChangeText={setAddress} placeholder="Osoite (valinnainen)"/><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.active]}><Text style={category===c?s.activeText:s.chipText}>{c}</Text></Pressable>)}</ScrollView><TextInput style={[s.input,s.description]} multiline value={description} onChangeText={setDescription} placeholder="Kuvaus"/><Pressable style={[s.publish,publishing&&{opacity:.5}]} disabled={publishing} onPress={publish}><Text style={s.publishText}>{publishing?'Julkaistaan...':'Julkaise ilmoitus'}</Text></Pressable></ScrollView></SafeAreaView></Modal></>;
}
const s=StyleSheet.create({fab:{position:'absolute',left:'50%',transform:[{translateX:-44}],bottom:74,zIndex:60,backgroundColor:'#1565d8',borderRadius:999,paddingHorizontal:18,paddingVertical:12,shadowColor:'#000',shadowOpacity:.18,shadowRadius:8,elevation:5},fabText:{color:'#fff',fontWeight:'900'},page:{flex:1,backgroundColor:'#f7f8fa'},head:{height:58,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderColor:'#e5e7eb'},link:{color:'#1565d8',fontWeight:'700'},title:{fontSize:18,fontWeight:'900'},form:{padding:16,gap:12,paddingBottom:40},photoBox:{backgroundColor:'#fff',borderRadius:16,borderWidth:1,borderColor:'#d8dee8',padding:22,alignItems:'center'},photoEmoji:{fontSize:40},photoTitle:{fontSize:17,fontWeight:'800',marginTop:6},help:{color:'#64748b',marginTop:4},previews:{gap:8},preview:{width:100,height:100,borderRadius:12},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d8dee8',borderRadius:12,padding:13,fontSize:16},description:{height:120,textAlignVertical:'top'},chips:{gap:8,paddingVertical:2},chip:{borderWidth:1,borderColor:'#d8dee8',borderRadius:999,paddingHorizontal:13,paddingVertical:9,backgroundColor:'#fff'},active:{backgroundColor:'#1565d8',borderColor:'#1565d8'},chipText:{color:'#334155'},activeText:{color:'#fff',fontWeight:'700'},publish:{backgroundColor:'#1565d8',borderRadius:12,padding:16,alignItems:'center',marginTop:6},publishText:{color:'#fff',fontWeight:'900',fontSize:16}});
