import React,{useEffect,useMemo,useState}from'react';
import{ActivityIndicator,FlatList,Image,Modal,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import MapView,{Marker}from'react-native-maps';
import{supabase}from'./supabase';

const categories=['Kaikki','Autot','Asunnot','Elektroniikka','Koti','Vaatteet','Työt','Palvelut'];
const CITY_COORDS={Helsinki:[60.1699,24.9384],Espoo:[60.2055,24.6559],Tampere:[61.4978,23.7610],Vantaa:[60.2934,25.0378],Oulu:[65.0121,25.4651],Turku:[60.4518,22.2666],Lahti:[60.9827,25.6615],Jyväskylä:[62.2426,25.7473],Kuopio:[62.8924,27.6770],Pori:[61.4851,21.7974],Kouvola:[60.8681,26.7042],Joensuu:[62.6010,29.7636],Lappeenranta:[61.0587,28.1887],Vaasa:[63.0951,21.6165],Rovaniemi:[66.5039,25.7294]};

function coordsFor(item){
 const lat=Number(item?.extra?.latitude??item?.latitude),lng=Number(item?.extra?.longitude??item?.longitude);
 if(Number.isFinite(lat)&&Number.isFinite(lng)&&lat&&lng)return{latitude:lat,longitude:lng};
 const c=CITY_COORDS[item?.city];return c?{latitude:c[0],longitude:c[1]}:null;
}

export default function ExploreOverlay(){
 const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[items,setItems]=useState([]),[view,setView]=useState('map');
 const[q,setQ]=useState(''),[city,setCity]=useState(''),[category,setCategory]=useState('Kaikki'),[minPrice,setMinPrice]=useState(''),[maxPrice,setMaxPrice]=useState(''),[sort,setSort]=useState('newest');
 async function load(){setLoading(true);let query=supabase.from('listings').select('*').limit(200);const{data}=await query;setItems(data||[]);setLoading(false)}
 useEffect(()=>{if(open)load()},[open]);
 const filtered=useMemo(()=>{const term=q.trim().toLowerCase(),min=Number(minPrice)||0,max=maxPrice?Number(maxPrice):Infinity;let out=items.filter(x=>{const p=Number(x.price)||0;return(!term||String(x.title||'').toLowerCase().includes(term)||String(x.description||'').toLowerCase().includes(term))&&(!city.trim()||String(x.city||'').toLowerCase().includes(city.trim().toLowerCase()))&&(category==='Kaikki'||x.category===category)&&p>=min&&p<=max});out=[...out];if(sort==='priceAsc')out.sort((a,b)=>(Number(a.price)||0)-(Number(b.price)||0));else if(sort==='priceDesc')out.sort((a,b)=>(Number(b.price)||0)-(Number(a.price)||0));else out.sort((a,b)=>new Date(b.created_at||0)-new Date(a.created_at||0));return out},[items,q,city,category,minPrice,maxPrice,sort]);
 const markers=filtered.map(x=>({item:x,coord:coordsFor(x)})).filter(x=>x.coord);
 return <><Pressable style={s.fab} onPress={()=>setOpen(true)}><Text style={s.fabText}>🗺️ Kartta</Text></Pressable><Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={s.page}><View style={s.head}><Pressable onPress={()=>setOpen(false)}><Text style={s.close}>Sulje</Text></Pressable><Text style={s.title}>Kartta & haku</Text><Text style={s.count}>{filtered.length}</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}><TextInput style={s.inputWide} value={q} onChangeText={setQ} placeholder="Mitä etsit?"/><TextInput style={s.input} value={city} onChangeText={setCity} placeholder="Kaupunki"/><TextInput style={s.inputSmall} value={minPrice} onChangeText={setMinPrice} keyboardType="numeric" placeholder="Min €"/><TextInput style={s.inputSmall} value={maxPrice} onChangeText={setMaxPrice} keyboardType="numeric" placeholder="Max €"/></ScrollView><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map(c=><Pressable key={c} onPress={()=>setCategory(c)} style={[s.chip,category===c&&s.active]}><Text style={category===c?s.activeText:s.chipText}>{c}</Text></Pressable>)}</ScrollView><View style={s.toolbar}><Pressable style={[s.toggle,view==='map'&&s.toggleActive]} onPress={()=>setView('map')}><Text>Kartta</Text></Pressable><Pressable style={[s.toggle,view==='list'&&s.toggleActive]} onPress={()=>setView('list')}><Text>Lista</Text></Pressable><Pressable style={s.sort} onPress={()=>setSort(sort==='newest'?'priceAsc':sort==='priceAsc'?'priceDesc':'newest')}><Text>{sort==='newest'?'Uusimmat':sort==='priceAsc'?'Hinta ↑':'Hinta ↓'}</Text></Pressable></View>{loading?<View style={s.center}><ActivityIndicator/></View>:view==='map'?<MapView style={s.map} initialRegion={{latitude:61.5,longitude:25.5,latitudeDelta:8,longitudeDelta:10}}>{markers.map(({item,coord})=><Marker key={String(item.id)} coordinate={coord} title={item.title} description={`${Number(item.price||0).toLocaleString('fi-FI')} € · ${item.city||''}`}/>)}</MapView>:<FlatList data={filtered} keyExtractor={x=>String(x.id)} contentContainerStyle={s.list} renderItem={({item})=><View style={s.card}>{item.image_urls?.[0]?<Image source={{uri:item.image_urls[0]}} style={s.thumb}/>:<View style={s.thumbEmpty}><Text>📦</Text></View>}<View style={{flex:1}}><Text style={s.cardTitle}>{item.title}</Text><Text style={s.price}>{Number(item.price||0).toLocaleString('fi-FI')} €</Text><Text style={s.meta}>{item.city||''} · {item.category||''}</Text></View></View>}/>}</SafeAreaView></Modal></>;
}
const s=StyleSheet.create({fab:{position:'absolute',right:14,bottom:76,zIndex:50,backgroundColor:'#fff',borderRadius:999,paddingHorizontal:16,paddingVertical:11,borderWidth:1,borderColor:'#dbe2ea',shadowColor:'#000',shadowOpacity:.12,shadowRadius:8,elevation:4},fabText:{fontWeight:'800',color:'#1565d8'},page:{flex:1,backgroundColor:'#f7f8fa'},head:{height:58,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderColor:'#e5e7eb'},close:{color:'#1565d8',fontWeight:'700'},title:{fontSize:18,fontWeight:'800'},count:{fontWeight:'800'},filters:{gap:8,padding:10,backgroundColor:'#fff'},input:{width:135,borderWidth:1,borderColor:'#d8dee8',borderRadius:12,paddingHorizontal:12,paddingVertical:10},inputWide:{width:190,borderWidth:1,borderColor:'#d8dee8',borderRadius:12,paddingHorizontal:12,paddingVertical:10},inputSmall:{width:95,borderWidth:1,borderColor:'#d8dee8',borderRadius:12,paddingHorizontal:12,paddingVertical:10},chips:{gap:8,paddingHorizontal:10,paddingVertical:8,backgroundColor:'#fff'},chip:{borderWidth:1,borderColor:'#dbe2ea',borderRadius:999,paddingHorizontal:13,paddingVertical:8},active:{backgroundColor:'#1565d8',borderColor:'#1565d8'},chipText:{color:'#334155'},activeText:{color:'#fff',fontWeight:'700'},toolbar:{flexDirection:'row',gap:8,padding:10},toggle:{backgroundColor:'#fff',borderRadius:10,paddingHorizontal:14,paddingVertical:10,borderWidth:1,borderColor:'#dbe2ea'},toggleActive:{backgroundColor:'#eaf2ff',borderColor:'#1565d8'},sort:{marginLeft:'auto',backgroundColor:'#fff',borderRadius:10,paddingHorizontal:14,paddingVertical:10,borderWidth:1,borderColor:'#dbe2ea'},map:{flex:1},center:{flex:1,alignItems:'center',justifyContent:'center'},list:{padding:12,gap:10},card:{backgroundColor:'#fff',borderRadius:14,padding:10,flexDirection:'row',gap:12,borderWidth:1,borderColor:'#e5e7eb'},thumb:{width:82,height:82,borderRadius:10},thumbEmpty:{width:82,height:82,borderRadius:10,backgroundColor:'#eef2f7',alignItems:'center',justifyContent:'center'},cardTitle:{fontSize:16,fontWeight:'800'},price:{fontSize:18,fontWeight:'900',marginTop:6},meta:{color:'#64748b',marginTop:4}});
