import React,{useState}from'react';
import{Alert,Image,Pressable,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import{listingImages,updateOwnListing}from'./listingFeatures';

export default function ListingDetail({listing,userId,isFavorite,onFavorite,onBack,onMessage,onReserve,onUpdated}){
 const own=listing.user_id===userId,[editing,setEditing]=useState(false),[title,setTitle]=useState(listing.title||''),[price,setPrice]=useState(String(listing.price||'')),[city,setCity]=useState(listing.city||''),[description,setDescription]=useState(listing.description||''),[saving,setSaving]=useState(false);const images=listingImages(listing);
 async function save(){setSaving(true);try{const updated=await updateOwnListing(userId,listing.id,{title:title.trim(),price:Number(price)||0,city:city.trim(),description:description.trim()});onUpdated(updated);setEditing(false)}catch(e){Alert.alert('Virhe',e.message)}finally{setSaving(false)}}
 return <ScrollView contentContainerStyle={s.page}><View style={s.top}><Pressable onPress={onBack}><Text style={s.link}>← Takaisin</Text></Pressable><Pressable onPress={onFavorite}><Text style={s.heart}>{isFavorite?'♥':'♡'}</Text></Pressable></View>{images.length?<ScrollView horizontal pagingEnabled showsHorizontalScrollIndicator={false}>{images.map((uri,i)=><Image key={`${uri}-${i}`} source={{uri}} style={s.hero}/>)}</ScrollView>:<View style={s.empty}><Text style={{fontSize:54}}>📦</Text></View>}<Text style={s.count}>{images.length?`${images.length} kuvaa`:''}</Text>{editing?<><TextInput style={s.input} value={title} onChangeText={setTitle}/><TextInput style={s.input} value={price} onChangeText={setPrice} keyboardType="numeric"/><TextInput style={s.input} value={city} onChangeText={setCity}/><TextInput style={[s.input,{height:120}]} multiline value={description} onChangeText={setDescription}/><Pressable style={s.primary} disabled={saving} onPress={save}><Text style={s.primaryText}>{saving?'Tallennetaan...':'Tallenna muutokset'}</Text></Pressable><Pressable style={s.secondary} onPress={()=>setEditing(false)}><Text>Peruuta</Text></Pressable></>:<><Text style={s.title}>{listing.title}</Text><Text style={s.price}>{Number(listing.price||0).toLocaleString('fi-FI')} €</Text><Text style={s.meta}>{listing.city||''} · {listing.category||''}</Text><Text style={s.description}>{listing.description||'Ei kuvausta.'}</Text>{own?<Pressable style={s.primary} onPress={()=>setEditing(true)}><Text style={s.primaryText}>Muokkaa ilmoitusta</Text></Pressable>:<View style={s.actions}><Pressable style={s.secondaryHalf} onPress={onMessage}><Text>💬 Viesti</Text></Pressable><Pressable style={s.primaryHalf} onPress={onReserve}><Text style={s.primaryText}>Varaa</Text></Pressable></View>}</>}</ScrollView>
}
const s=StyleSheet.create({page:{padding:16,paddingBottom:48,backgroundColor:'#fff'},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:12},link:{color:'#1565d8',fontWeight:'700'},heart:{fontSize:36,color:'#d7263d'},hero:{width:360,height:300,borderRadius:18,marginRight:10,backgroundColor:'#eef2f7'},empty:{height:260,borderRadius:18,backgroundColor:'#eef2f7',alignItems:'center',justifyContent:'center'},count:{color:'#64748b',marginTop:6},title:{fontSize:26,fontWeight:'800',marginTop:16},price:{fontSize:24,fontWeight:'800',marginTop:8},meta:{color:'#64748b',marginTop:5},description:{fontSize:16,lineHeight:24,marginVertical:20},input:{borderWidth:1,borderColor:'#d8dee9',borderRadius:12,padding:13,marginTop:12,fontSize:16},primary:{backgroundColor:'#1565d8',borderRadius:12,padding:15,alignItems:'center',marginTop:12},primaryText:{color:'#fff',fontWeight:'800'},secondary:{borderWidth:1,borderColor:'#cbd5e1',borderRadius:12,padding:15,alignItems:'center',marginTop:10},actions:{flexDirection:'row',gap:10,marginTop:12},secondaryHalf:{flex:1,borderWidth:1,borderColor:'#cbd5e1',borderRadius:12,padding:15,alignItems:'center'},primaryHalf:{flex:1,backgroundColor:'#1565d8',borderRadius:12,padding:15,alignItems:'center'}});
