import React,{useEffect,useState}from'react';
import{ActivityIndicator,Alert,FlatList,Modal,Pressable,SafeAreaView,StyleSheet,Text,TextInput,View}from'react-native';
import MapView,{Marker}from'react-native-maps';
import * as Location from'expo-location';
import{supabase}from'./supabase';

const FALLBACK={latitude:60.9827,longitude:25.6615,latitudeDelta:.08,longitudeDelta:.08};

export default function LocationManager(){
 const[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[items,setItems]=useState([]),[selected,setSelected]=useState(null),[address,setAddress]=useState(''),[point,setPoint]=useState(null),[saving,setSaving]=useState(false);
 async function loadOwn(){setLoading(true);const{data:{session}}=await supabase.auth.getSession();if(!session){setItems([]);setLoading(false);return}const{data,error}=await supabase.from('listings').select('id,title,city,address,latitude,longitude').eq('user_id',session.user.id).order('created_at',{ascending:false});if(error)Alert.alert('Virhe',error.message);setItems(data||[]);setLoading(false)}
 useEffect(()=>{if(open)loadOwn()},[open]);
 function choose(item){setSelected(item);setAddress(item.address||'');const lat=Number(item.latitude),lng=Number(item.longitude);setPoint(Number.isFinite(lat)&&Number.isFinite(lng)&&lat&&lng?{latitude:lat,longitude:lng}:null)}
 async function useCurrent(){try{const p=await Location.requestForegroundPermissionsAsync();if(p.status!=='granted')return Alert.alert('Sijainti','Salli sijainnin käyttö asetuksista.');const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setPoint({latitude:pos.coords.latitude,longitude:pos.coords.longitude})}catch(e){Alert.alert('Sijainti',e.message)}}
 async function save(){if(!selected||!point)return Alert.alert('Sijainti','Valitse piste kartalta.');setSaving(true);try{const{data:{session}}=await supabase.auth.getSession();const{error}=await supabase.from('listings').update({address:address.trim(),latitude:point.latitude,longitude:point.longitude}).eq('id',selected.id).eq('user_id',session.user.id);if(error)throw error;Alert.alert('Tallennettu','Tarkka sijainti päivitettiin.');await loadOwn();setSelected(null);setPoint(null);setAddress('')}catch(e){Alert.alert('Virhe',e.message)}finally{setSaving(false)}}
 return <><Pressable style={s.fab} onPress={()=>setOpen(true)}><Text style={s.fabText}>📍 Sijainti</Text></Pressable><Modal visible={open} animationType="slide" onRequestClose={()=>setOpen(false)}><SafeAreaView style={s.page}><View style={s.head}><Pressable onPress={()=>setOpen(false)}><Text style={s.link}>Sulje</Text></Pressable><Text style={s.title}>Ilmoituksen sijainti</Text><View style={{width:38}}/></View>{loading?<View style={s.center}><ActivityIndicator/></View>:!selected?<FlatList data={items} keyExtractor={x=>String(x.id)} contentContainerStyle={s.list} ListHeaderComponent={<Text style={s.help}>Valitse oma ilmoitus ja määritä sille tarkka osoite ja piste kartalta.</Text>} ListEmptyComponent={<Text style={s.help}>Sinulla ei ole vielä ilmoituksia.</Text>} renderItem={({item})=><Pressable style={s.row} onPress={()=>choose(item)}><View style={{flex:1}}><Text style={s.itemTitle}>{item.title}</Text><Text style={s.meta}>{item.address||item.city||'Ei osoitetta'}</Text></View><Text style={s.chev}>›</Text></Pressable>}/>:<View style={s.editor}><View style={s.subhead}><Pressable onPress={()=>setSelected(null)}><Text style={s.link}>← Takaisin</Text></Pressable><Text style={s.itemTitle}>{selected.title}</Text></View><TextInput style={s.input} value={address} onChangeText={setAddress} placeholder="Osoite, esim. Aleksanterinkatu 10"/><Pressable style={s.current} onPress={useCurrent}><Text style={s.currentText}>◎ Käytä nykyistä sijaintia</Text></Pressable><Text style={s.help}>Paina karttaa pitkään tai siirrä punaista merkkiä oikeaan kohtaan.</Text><MapView style={s.map} initialRegion={point?{...point,latitudeDelta:.02,longitudeDelta:.02}:FALLBACK} onLongPress={e=>setPoint(e.nativeEvent.coordinate)}>{point&&<Marker draggable coordinate={point} onDragEnd={e=>setPoint(e.nativeEvent.coordinate)}/>}</MapView>{point&&<Text style={s.coords}>{point.latitude.toFixed(6)}, {point.longitude.toFixed(6)}</Text>}<Pressable style={[s.save,saving&&{opacity:.5}]} disabled={saving} onPress={save}><Text style={s.saveText}>{saving?'Tallennetaan...':'Tallenna sijainti'}</Text></Pressable></View>}</SafeAreaView></Modal></>;
}
const s=StyleSheet.create({fab:{position:'absolute',left:14,bottom:76,zIndex:49,backgroundColor:'#fff',borderRadius:999,paddingHorizontal:15,paddingVertical:11,borderWidth:1,borderColor:'#dbe2ea',shadowColor:'#000',shadowOpacity:.12,shadowRadius:8,elevation:4},fabText:{fontWeight:'800',color:'#1565d8'},page:{flex:1,backgroundColor:'#f7f8fa'},head:{height:58,backgroundColor:'#fff',flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:16,borderBottomWidth:1,borderColor:'#e5e7eb'},title:{fontSize:18,fontWeight:'800'},link:{color:'#1565d8',fontWeight:'700'},center:{flex:1,alignItems:'center',justifyContent:'center'},list:{padding:16,gap:10},help:{color:'#64748b',lineHeight:21,marginBottom:8},row:{backgroundColor:'#fff',borderRadius:14,padding:15,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#e5e7eb'},itemTitle:{fontSize:16,fontWeight:'800'},meta:{color:'#64748b',marginTop:4},chev:{fontSize:28,color:'#94a3b8'},editor:{flex:1,padding:14,gap:10},subhead:{flexDirection:'row',alignItems:'center',gap:12},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#d8dee8',borderRadius:12,padding:13},current:{backgroundColor:'#eaf2ff',borderRadius:12,padding:13,alignItems:'center'},currentText:{color:'#1565d8',fontWeight:'800'},map:{flex:1,minHeight:330,borderRadius:16},coords:{textAlign:'center',color:'#64748b'},save:{backgroundColor:'#1565d8',borderRadius:12,padding:15,alignItems:'center',marginBottom:10},saveText:{color:'#fff',fontWeight:'800'}});
