import React,{useEffect,useState}from'react';
import{Alert,Linking,Pressable,ScrollView,Switch,Text,TextInput,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{supabase}from'./supabase';

const DEFAULT_FLAGS={notifications:true,messages:true,reservations:true,diili:true,searchAlerts:true,location:true,showPhone:true,showCity:true,online:false};
const LANGUAGES=[['fi','Suomi'],['en','English'],['fa','فارسی'],['ru','Русский']];
const THEMES=[['system','Järjestelmän mukaan'],['light','Vaalea'],['dark','Tumma']];

export default function SettingsScreen({session,onBack}){
 const[screen,setScreen]=useState('main');
 const[language,setLanguage]=useState('fi');
 const[theme,setTheme]=useState('system');
 const[flags,setFlags]=useState(DEFAULT_FLAGS);
 const[newPassword,setNewPassword]=useState('');
 const[newPassword2,setNewPassword2]=useState('');
 const[name,setName]=useState(session?.user?.user_metadata?.display_name||'');
 const[phone,setPhone]=useState(session?.user?.user_metadata?.phone||'');
 const[city,setCity]=useState(session?.user?.user_metadata?.city||'');

 useEffect(()=>{(async()=>{try{const raw=await AsyncStorage.getItem('kaikki.settings');if(!raw)return;const x=JSON.parse(raw);if(x.language)setLanguage(x.language);if(x.theme)setTheme(x.theme);if(x.flags)setFlags(v=>({...v,...x.flags}))}catch(e){console.warn('settings load',e?.message)}})()},[]);
 async function save(next={}){const data={language:next.language??language,theme:next.theme??theme,flags:next.flags??flags};try{await AsyncStorage.setItem('kaikki.settings',JSON.stringify(data))}catch(e){console.warn('settings save',e?.message)}}
 async function toggle(key,value){const next={...flags,[key]:value};setFlags(next);await save({flags:next})}
 async function chooseLanguage(code){setLanguage(code);await save({language:code});setScreen('main')}
 async function chooseTheme(code){setTheme(code);await save({theme:code});setScreen('main')}
 async function updatePassword(){if(newPassword.length<8)return Alert.alert('Salasana','Salasanassa pitää olla vähintään 8 merkkiä.');if(newPassword!==newPassword2)return Alert.alert('Salasana','Salasanat eivät täsmää.');const{error}=await supabase.auth.updateUser({password:newPassword});if(error)return Alert.alert('Virhe',error.message);setNewPassword('');setNewPassword2('');Alert.alert('Valmis','Salasana vaihdettiin.');setScreen('main')}
 async function saveProfile(){const{error}=await supabase.auth.updateUser({data:{...(session?.user?.user_metadata||{}),display_name:name.trim(),phone:phone.trim(),city:city.trim()}});if(error)return Alert.alert('Virhe',error.message);Alert.alert('Tallennettu','Tilin tiedot päivitettiin.');setScreen('main')}
 function signOutEverywhere(){Alert.alert('Kirjaudu ulos kaikilta laitteilta','Haluatko varmasti kirjautua ulos kaikilta laitteilta?',[{text:'Peruuta',style:'cancel'},{text:'Kirjaudu ulos',style:'destructive',onPress:async()=>{const{error}=await supabase.auth.signOut({scope:'global'});if(error)Alert.alert('Virhe',error.message)}}])}
 function deleteAccount(){Alert.alert('Poista tili','Tämä poistaa tilisi ja omat tietosi pysyvästi. Haluatko jatkaa?',[{text:'Peruuta',style:'cancel'},{text:'Poista tili',style:'destructive',onPress:async()=>{const{error}=await supabase.rpc('delete_my_account');if(error)return Alert.alert('Tilin poisto',error.message);await supabase.auth.signOut()}}])}
 const languageName=LANGUAGES.find(x=>x[0]===language)?.[1]||'Suomi';
 const themeName=THEMES.find(x=>x[0]===theme)?.[1]||'Järjestelmän mukaan';
 const bg=theme==='dark'?'#111827':'#f6f7f9',card=theme==='dark'?'#1f2937':'#fff',text=theme==='dark'?'#fff':'#111827',muted=theme==='dark'?'#cbd5e1':'#718096';
 const Row=({title,subtitle,onPress,last=false,danger=false})=><Pressable onPress={onPress} hitSlop={6} style={({pressed})=>({minHeight:76,paddingHorizontal:16,paddingVertical:12,borderBottomWidth:last?0:1,borderBottomColor:theme==='dark'?'#374151':'#e7ebf0',flexDirection:'row',alignItems:'center',backgroundColor:pressed?(theme==='dark'?'#263244':'#f3f6fa'):'transparent'})}><View style={{flex:1}}><Text style={{fontSize:17,fontWeight:'800',color:danger?'#dc2626':text}}>{title}</Text>{subtitle?<Text style={{fontSize:13.5,color:muted,marginTop:4}}>{subtitle}</Text>:null}</View><Text style={{fontSize:30,color:'#b7bcc5'}}>›</Text></Pressable>;
 const Toggle=({title,subtitle,k,last=false})=><View style={{minHeight:76,paddingHorizontal:16,paddingVertical:12,borderBottomWidth:last?0:1,borderBottomColor:theme==='dark'?'#374151':'#e7ebf0',flexDirection:'row',alignItems:'center'}}><Pressable onPress={()=>toggle(k,!flags[k])} style={{flex:1,paddingVertical:8}}><Text style={{fontSize:17,fontWeight:'800',color:text}}>{title}</Text>{subtitle?<Text style={{fontSize:13.5,color:muted,marginTop:4}}>{subtitle}</Text>:null}</Pressable><Switch value={!!flags[k]} onValueChange={v=>toggle(k,v)}/></View>;
 const Header=({title='Asetukset',back=()=>setScreen('main')})=><View style={{height:64,backgroundColor:card,flexDirection:'row',alignItems:'center',justifyContent:'center',borderBottomWidth:1,borderBottomColor:theme==='dark'?'#374151':'#e5e7eb'}}><Pressable onPress={back} hitSlop={10} style={{position:'absolute',left:12,padding:10}}><Text style={{fontSize:36,color:'#1565d8',lineHeight:36}}>‹</Text></Pressable><Text style={{fontSize:23,fontWeight:'900',color:text}}>{title}</Text></View>;
 const Section=({title,children})=><><Text style={{marginHorizontal:20,marginTop:18,marginBottom:7,fontSize:14,fontWeight:'800',color:muted}}>{title}</Text><View style={{marginHorizontal:16,backgroundColor:card,borderRadius:18,overflow:'hidden',borderWidth:1,borderColor:theme==='dark'?'#374151':'#e5e7eb'}}>{children}</View></>;
 if(screen==='language')return <ScrollView style={{flex:1,backgroundColor:bg}} contentContainerStyle={{paddingBottom:120}}><Header title="Kieli"/>{LANGUAGES.map(([code,label])=><Pressable key={code} onPress={()=>chooseLanguage(code)} style={{marginHorizontal:16,marginTop:12,backgroundColor:card,borderRadius:14,padding:18,borderWidth:language===code?2:1,borderColor:language===code?'#1565d8':'#e5e7eb',flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontSize:18,fontWeight:'800',color:text}}>{label}</Text><Text style={{fontSize:22,color:'#1565d8'}}>{language===code?'✓':''}</Text></Pressable>)}</ScrollView>;
 if(screen==='theme')return <ScrollView style={{flex:1,backgroundColor:bg}} contentContainerStyle={{paddingBottom:120}}><Header title="Teema"/>{THEMES.map(([code,label])=><Pressable key={code} onPress={()=>chooseTheme(code)} style={{marginHorizontal:16,marginTop:12,backgroundColor:card,borderRadius:14,padding:18,borderWidth:theme===code?2:1,borderColor:theme===code?'#1565d8':'#e5e7eb',flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontSize:18,fontWeight:'800',color:text}}>{label}</Text><Text style={{fontSize:22,color:'#1565d8'}}>{theme===code?'✓':''}</Text></Pressable>)}</ScrollView>;
 if(screen==='password')return <ScrollView style={{flex:1,backgroundColor:bg}} contentContainerStyle={{padding:20,paddingBottom:120,gap:14}}><Pressable onPress={()=>setScreen('main')}><Text style={{color:'#1565d8',fontWeight:'800'}}>← Asetukset</Text></Pressable><Text style={{fontSize:28,fontWeight:'900',color:text}}>Vaihda salasana</Text><TextInput style={{backgroundColor:card,borderWidth:1,borderColor:'#d8dde5',borderRadius:13,padding:14,color:text}} secureTextEntry value={newPassword} onChangeText={setNewPassword} placeholder="Uusi salasana" placeholderTextColor={muted}/><TextInput style={{backgroundColor:card,borderWidth:1,borderColor:'#d8dde5',borderRadius:13,padding:14,color:text}} secureTextEntry value={newPassword2} onChangeText={setNewPassword2} placeholder="Uusi salasana uudelleen" placeholderTextColor={muted}/><Pressable onPress={updatePassword} style={{backgroundColor:'#1565d8',borderRadius:13,padding:15,alignItems:'center'}}><Text style={{color:'#fff',fontWeight:'900'}}>Vaihda salasana</Text></Pressable></ScrollView>;
 if(screen==='profile')return <ScrollView style={{flex:1,backgroundColor:bg}} contentContainerStyle={{padding:20,paddingBottom:120,gap:14}}><Pressable onPress={()=>setScreen('main')}><Text style={{color:'#1565d8',fontWeight:'800'}}>← Asetukset</Text></Pressable><Text style={{fontSize:28,fontWeight:'900',color:text}}>Muokkaa tiliä</Text>{[['Nimi',name,setName],['Puhelinnumero',phone,setPhone],['Kaupunki',city,setCity]].map(([p,v,setter])=><TextInput key={p} style={{backgroundColor:card,borderWidth:1,borderColor:'#d8dde5',borderRadius:13,padding:14,color:text}} value={v} onChangeText={setter} placeholder={p} placeholderTextColor={muted}/>) }<Pressable onPress={saveProfile} style={{backgroundColor:'#1565d8',borderRadius:13,padding:15,alignItems:'center'}}><Text style={{color:'#fff',fontWeight:'900'}}>Tallenna</Text></Pressable></ScrollView>;
 if(['about','terms','privacy'].includes(screen)){const title={about:'Tietoja sovelluksesta',terms:'Käyttöehdot',privacy:'Tietosuojaseloste'}[screen];const body={about:'Kaikki.fi on suomalainen markkinapaikka tavaroiden, asuntojen, palveluiden ja muun ostamiseen ja myymiseen.\n\nVersio 0.5.20',terms:'Kaikki.fi-palvelua tulee käyttää Suomen lakien ja palvelun sääntöjen mukaisesti. Käyttäjä vastaa ilmoittamiensa tietojen oikeellisuudesta ja omasta kaupankäynnistään.',privacy:'Kaikki.fi käsittelee käyttäjän tietoja palvelun tuottamista, turvallisuutta ja tilin toimintaa varten. Käyttäjä voi hallita tilinsä tietoja ja pyytää tilin poistamista.'}[screen];return <ScrollView style={{flex:1,backgroundColor:bg}} contentContainerStyle={{paddingBottom:120}}><Header title={title}/><View style={{margin:16,padding:18,backgroundColor:card,borderRadius:16}}><Text style={{fontSize:16,lineHeight:24,color:text}}>{body}</Text></View></ScrollView>}
 return <ScrollView style={{flex:1,backgroundColor:bg}} contentContainerStyle={{paddingBottom:120}} keyboardShouldPersistTaps="handled"><Header back={onBack}/><Section title="Kaikki.fi"><Toggle title="Ilmoitukset" subtitle="Käytössä" k="notifications"/><Row title="Kieli" subtitle={languageName} onPress={()=>setScreen('language')}/><Row title="Teema" subtitle={themeName} onPress={()=>setScreen('theme')} last/></Section><Section title="Ilmoitukset"><Toggle title="Viestit" subtitle="Uudet viestit" k="messages"/><Toggle title="Varaukset" subtitle="Varausten muutokset" k="reservations"/><Toggle title="Kaikki Diili" subtitle="Diilin tapahtumat" k="diili"/><Toggle title="Hakuvahdit" subtitle="Tallennettujen hakujen osumat" k="searchAlerts" last/></Section><Section title="Yksityisyys"><Toggle title="Sijainti" subtitle="Käytä sijaintia sovelluksessa" k="location"/><Toggle title="Näytä puhelinnumero" subtitle="Muille käyttäjille" k="showPhone"/><Toggle title="Näytä kaupunki" subtitle="Profiilissa ja ilmoituksissa" k="showCity"/><Toggle title="Online-tila" subtitle="Näytä milloin olet paikalla" k="online" last/></Section><Section title="Turvallisuus ja tili"><Row title="Vaihda salasana" subtitle="Päivitä tilisi salasana" onPress={()=>setScreen('password')}/><Row title="Kirjaudu ulos kaikilta laitteilta" subtitle="Suojaa tiliäsi" onPress={signOutEverywhere}/><Row title="Muokkaa tiliä" subtitle="Nimi, puhelin ja kaupunki" onPress={()=>setScreen('profile')}/><Row title="Poista tili" subtitle="Poista tili ja omat tiedot" onPress={deleteAccount} last danger/></Section><Section title="Puhelimen asetukset"><Row title="Sovellusluvat" subtitle="Kamera, mikrofoni, sijainti ja ilmoitukset" onPress={()=>Linking.openSettings()} last/></Section><Section title="Tietoja"><Row title="Tietoja sovelluksesta" subtitle="Kaikki.fi" onPress={()=>setScreen('about')}/><Row title="Käyttöehdot" subtitle="Palvelun käyttöehdot" onPress={()=>setScreen('terms')}/><Row title="Tietosuojaseloste" subtitle="Miten tietojasi käsitellään" onPress={()=>setScreen('privacy')} last/></Section></ScrollView>;
}
